import './globals.css';
import { Metadata } from 'next';
import { CartProvider } from '@/app/context/CartContext'; // Adjust path if needed
import { ReactNode } from 'react';


export const metadata: Metadata = {
  title: 'Hackathon',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        {/* Wrapping the app in CartProvider to provide cart context globally */}
        <CartProvider>
        
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
